In [18]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the dataset

In [29]:
dataset = pd.read_csv("./retail_sales.csv")
#Manually creating a array to track which are the Numerical columns from the given DATA
numeric_columns = ['Quantity','Price','Sales']
#this will convert the columns to numeric data type which removes
#error due to absence of data
for col in numeric_columns:
    dataset[col] = pd.to_numeric(dataset[col], errors='coerce')
    
print(dataset.dtypes)

numerical_cols = dataset.select_dtypes(
    include=['int64','float64']
).columns 

categorical_cols = dataset.select_dtypes(
    include=['object','str']
).columns

X = dataset.iloc[:,1:5].values
Y = dataset.iloc[:,[0,5,6,7]].values
Z = dataset.iloc[:, -1].values

print(Y)
print(Z)

OrderID              int64
State                  str
City                   str
Product                str
Category               str
Quantity             int64
Price              float64
Sales              float64
Eligible_For_AI        str
dtype: object
[[  1001.      2.  55000. 110000.]
 [  1002.      3.  30000.  90000.]
 [  1003.      5.     nan  10000.]
 [  1004.      2.  15000.  30000.]
 [  1005.     10.   1500.  15000.]
 [  1006.      8.    700.   5600.]
 [  1007.      4.  25000. 100000.]
 [  1008.      1.  60000.     nan]
 [  1009.      2.     nan     nan]
 [  1010.      3.  12000.  36000.]
 [  1011.      2.  45000.  90000.]
 [  1012.      6.   3500.  21000.]
 [  1013.      5.  32000. 160000.]
 [  1014.      7.   8000.  56000.]
 [  1015.      2.  58000. 116000.]]
<StringArray>
['yes', 'yes',  'no', 'yes',  'no',  'no', 'yes', 'yes',   nan, 'yes', 'yes',
  'no', 'yes',  'no', 'yes']
Length: 15, dtype: str


Fill the missing data so that it can be consistent

In [33]:
from sklearn.impute import SimpleImputer

data = np.array(Y)
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
Y = imputer.fit_transform(data)
np.set_printoptions(suppress=True)
print(X)
print(Y)

[['Karnataka' 'Bangalore' 'Laptop' 'Electronics']
 ['Maharashtra' 'Mumbai' 'Phone' 'Electronics']
 ['Telangana' 'Hyderabad' 'Headphones' 'Accessories']
 ['Tamil Nadu' 'Chennai' 'Monitor' 'Electronics']
 ['Delhi' 'New Delhi' 'Keyboard' 'Accessories']
 ['Karnataka' 'Mysore' 'Mouse' 'Accessories']
 ['West Bengal' 'Kolkata' 'Tablet' 'Electronics']
 ['Maharashtra' 'Pune' 'Laptop' 'Electronics']
 ['Gujarat' 'Ahmedabad' 'Phone' 'Electronics']
 ['Rajasthan' 'Jaipur' 'Printer' 'Electronics']
 ['Uttar Pradesh' 'Lucknow' 'Camera' 'Electronics']
 ['Kerala' 'Kochi' 'Speaker' 'Accessories']
 ['Karnataka' 'Bangalore' 'Phone' 'Electronics']
 ['Maharashtra' 'Mumbai' 'Smart Watch' 'Accessories']
 ['Telangana' 'Hyderabad' 'Laptop' 'Electronics']]
[[  1001.              2.          55000.         110000.        ]
 [  1002.              3.          30000.          90000.        ]
 [  1003.              5.          26592.30769231  10000.        ]
 [  1004.              2.          15000.          30000.    

Encoding the Independent Variable

In [41]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
 
ct = ColumnTransformer(transformers=[('encoder', 
                       OneHotEncoder(sparse_output=False),
                       [0])],
                       remainder='passthrough')
X = ct.fit_transform(X)
print(X)

TypeError: Sparse data was passed, but dense data is required. Use '.toarray()' to convert to a dense numpy array.

Encoding the Dependent Variable

In [42]:
from sklearn.preprocessing import  LabelEncoder

le = LabelEncoder()
Z = le.fit_transform(Z)
print(Z) 

[1 1 0 1 0 0 1 1 2 1 1 0 1 0 1]
