In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the dataset

In [8]:
dataset = pd.read_csv("./retail_sales.csv")
X = dataset.iloc[:, :-3].values 
#here the first colon represents that we are taking all the rows
#the second colon :-3 represents that last 3 columns should be avoided this is needed 
#because the last 3 columns of the data give us details that we need to make decisions
Y = dataset.iloc[:, -3:].values
print(X)
print(Y)

[[1001 'Karnataka' 'Bangalore' 'Laptop' 'Electronics']
 [1002 'Maharashtra' 'Mumbai' 'Phone' 'Electronics']
 [1003 'Telangana' 'Hyderabad' 'Headphones' 'Accessories']
 [1004 'Tamil Nadu' 'Chennai' 'Monitor' 'Electronics']
 [1005 'Delhi' 'New Delhi' 'Keyboard' 'Accessories']
 [1006 'Karnataka' 'Mysore' 'Mouse' 'Accessories']
 [1007 'West Bengal' 'Kolkata' 'Tablet' 'Electronics']
 [1008 'Maharashtra' 'Pune' 'Laptop' 'Electronics']
 [1009 'Gujarat' 'Ahmedabad' 'Phone' 'Electronics']
 [1010 'Rajasthan' 'Jaipur' 'Printer' 'Electronics']
 [1011 'Uttar Pradesh' 'Lucknow' 'Camera' 'Electronics']
 [1012 'Kerala' 'Kochi' 'Speaker' 'Accessories']
 [1013 'Karnataka' 'Bangalore' 'Phone' 'Electronics']
 [1014 'Maharashtra' 'Mumbai' 'Smart Watch' 'Accessories']
 [1015 'Telangana' 'Hyderabad' 'Laptop' 'Electronics']]
[[     2  55000 110000]
 [     3  30000  90000]
 [     5   2000  10000]
 [     2  15000  30000]
 [    10   1500  15000]
 [     8    700   5600]
 [     4  25000 100000]
 [     1  60000  60