In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the dataset

In [2]:
dataset = pd.read_csv("./retail_sales.csv")
#Manually creating a array to track which are the Numerical columns from the given DATA
numeric_columns = ['Quantity','Price','Sales']
#this will convert the columns to numeric data type which removes
#error due to absence of data
for col in numeric_columns:
    dataset[col] = pd.to_numeric(dataset[col], errors='coerce')
    
print(dataset.dtypes)

numerical_cols = dataset.select_dtypes(
    include=['int64','float64']
).columns 

categorical_cols = dataset.select_dtypes(
    include=['object','str']
).columns

X = dataset.iloc[:,1:5].values
Y = dataset.iloc[:,[0,5,6,7]].values
Z = dataset.iloc[:, -1].values

print(Y)
print(Z)

OrderID              int64
State                  str
City                   str
Product                str
Category               str
Quantity             int64
Price              float64
Sales              float64
Eligible_For_AI        str
dtype: object
[[1.001e+03 2.000e+00 5.500e+04 1.100e+05]
 [1.002e+03 3.000e+00 3.000e+04 9.000e+04]
 [1.003e+03 5.000e+00       nan 1.000e+04]
 [1.004e+03 2.000e+00 1.500e+04 3.000e+04]
 [1.005e+03 1.000e+01 1.500e+03 1.500e+04]
 [1.006e+03 8.000e+00 7.000e+02 5.600e+03]
 [1.007e+03 4.000e+00 2.500e+04 1.000e+05]
 [1.008e+03 1.000e+00 6.000e+04       nan]
 [1.009e+03 2.000e+00       nan       nan]
 [1.010e+03 3.000e+00 1.200e+04 3.600e+04]
 [1.011e+03 2.000e+00 4.500e+04 9.000e+04]
 [1.012e+03 6.000e+00 3.500e+03 2.100e+04]
 [1.013e+03 5.000e+00 3.200e+04 1.600e+05]
 [1.014e+03 7.000e+00 8.000e+03 5.600e+04]
 [1.015e+03 2.000e+00 5.800e+04 1.160e+05]]
<StringArray>
['yes', 'yes',  'no', 'yes',  'no',  'no', 'yes', 'yes',   nan, 'yes', 'yes',
  'no

Fill the missing data so that it can be consistent

In [3]:
from sklearn.impute import SimpleImputer

data = np.array(Y)
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
Y = imputer.fit_transform(data)
np.set_printoptions(suppress=True)
print(X)
print(Y)

[['Karnataka' 'Bangalore' 'Laptop' 'Electronics']
 ['Maharashtra' 'Mumbai' 'Phone' 'Electronics']
 ['Telangana' 'Hyderabad' 'Headphones' 'Accessories']
 ['Tamil Nadu' 'Chennai' 'Monitor' 'Electronics']
 ['Delhi' 'New Delhi' 'Keyboard' 'Accessories']
 ['Karnataka' 'Mysore' 'Mouse' 'Accessories']
 ['West Bengal' 'Kolkata' 'Tablet' 'Electronics']
 ['Maharashtra' 'Pune' 'Laptop' 'Electronics']
 ['Gujarat' 'Ahmedabad' 'Phone' 'Electronics']
 ['Rajasthan' 'Jaipur' 'Printer' 'Electronics']
 ['Uttar Pradesh' 'Lucknow' 'Camera' 'Electronics']
 ['Kerala' 'Kochi' 'Speaker' 'Accessories']
 ['Karnataka' 'Bangalore' 'Phone' 'Electronics']
 ['Maharashtra' 'Mumbai' 'Smart Watch' 'Accessories']
 ['Telangana' 'Hyderabad' 'Laptop' 'Electronics']]
[[  1001.              2.          55000.         110000.        ]
 [  1002.              3.          30000.          90000.        ]
 [  1003.              5.          26592.30769231  10000.        ]
 [  1004.              2.          15000.          30000.    

Encoding the Independent Variable

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
 
ct = ColumnTransformer(transformers=[('encoder', 
                       OneHotEncoder(),
                       [0])],
                       remainder='passthrough')
X = ct.fit_transform(X)
print(X)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Bangalore' 'Laptop'
  'Electronics']
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 'Mumbai' 'Phone' 'Electronics']
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 'Hyderabad' 'Headphones'
  'Accessories']
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 'Chennai' 'Monitor'
  'Electronics']
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'New Delhi' 'Keyboard'
  'Accessories']
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Mysore' 'Mouse' 'Accessories']
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 'Kolkata' 'Tablet'
  'Electronics']
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 'Pune' 'Laptop' 'Electronics']
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Ahmedabad' 'Phone'
  'Electronics']
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 'Jaipur' 'Printer'
  'Electronics']
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 'Lucknow' 'Camera'
  'Electronics']
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 'Kochi' 'Speaker' 'Accessories']
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Bangalore' 'Phone'
  'E

Encoding the Dependent Variable

In [5]:
from sklearn.preprocessing import  LabelEncoder

le = LabelEncoder()
Z = le.fit_transform(Z)
print(Z) 

[1 1 0 1 0 0 1 1 2 1 1 0 1 0 1]


Splitting the dataset into the Training and Test set

In [ ]:
from sklearn.model_selection import train_test_split

